"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/. Do not edit by hand. The students'
agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete public
registry metadata used by the browser relay and the injected harness entry.

This template targets Spades. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import EnvironmentMeta

from .spades import default_action, extract_overlay, make_env

ENV_ID = "spades"
PLAYER_SLOT = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "spades",
        "display_name": "Spades",
        "description": (
            "Four-player partnership Spades: bid the tricks you will take, then follow suit and play "
            "them out with spades trump. Your agent play in teams."
        ),
        "min_slots": 4,
        "max_slots": 4,
        "human_slots": ("player_0", "player_1", "player_2", "player_3"),
        "human_timeout_ms": 60000,
        "recommended_episode_ticks": 56,
        "pace_interval_ms": None,
        "step_limit_ms": 1000,
        "episode_limit_ms": 120000,
        "messaging": True,
        "message_cap": 120,
        "llm": True,
        "renderer": "spades",
        "seat_order_matters": True,
        "view_interval_ms": 3000,
        "live_interval_ms": 900,
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "default_action",
    "ENV_ID",
    "PLAYER_SLOT",
    "META",
]
