"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/. Do not edit by hand. The students'
agents run against this vanilla-PettingZoo env locally; only the steppable environment is
synced, never the harness, recording store, or metadata layer.

This template targets Spades. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from .spades import AUTO_ACTION, extract_overlay, make_env, make_human_controller

ENV_ID = "spades"
PLAYER_SLOT = "player_0"

__all__ = [
    "make_env",
    "make_human_controller",
    "extract_overlay",
    "AUTO_ACTION",
    "ENV_ID",
    "PLAYER_SLOT",
]
