"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/. Do not edit by hand. The students'
agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete public
registry metadata used by the browser relay and the injected harness entry.

This template targets Hearts. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import EnvironmentMeta

from .hearts import default_action, extract_overlay, make_env

ENV_ID = "hearts"
PLAYER_SLOT = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "hearts",
        "display_name": "Hearts",
        "description": (
            "Four-player trick-taking Hearts: follow suit, avoid taking hearts and the queen of "
            "spades. Or, shoot the moon by taking them all to flip the score!"
        ),
        "min_slots": 4,
        "max_slots": 4,
        "human_slots": ("player_0", "player_1", "player_2", "player_3"),
        "human_timeout_ms": 60000,
        "recommended_episode_ticks": 52,
        "pace_interval_ms": None,
        "step_limit_ms": 1000,
        "episode_limit_ms": 120000,
        "messaging": False,
        "message_cap": None,
        "llm": True,
        "renderer": "hearts",
        "seat_order_matters": True,
        "view_interval_ms": 3000,
        "live_interval_ms": 900,
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "default_action",
    "ENV_ID",
    "PLAYER_SLOT",
    "META",
]
