"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/game_sandbox_environments/. Do not
edit by hand. The students' agents run against this vanilla-PettingZoo env locally; only the
steppable environment is synced, never the harness, recording store, or metadata layer.
"""
