/** The planned bundled art contract for the Hearthside Ink renderer. */
interface ThreeBranchesAsset {
  name: ThreeBranchesAssetName
  source: `./source-art/${string}`
  path: `./assets/${string}`
  width: number
  height: number
  tintable: boolean
  consumer: string
  frames?: ThreeBranchesFrameGrid
}

interface ThreeBranchesFrameGrid {
  width: number
  height: number
  columns: readonly string[]
  rows: readonly string[]
}

const CHARACTER_HAND_FRAMES = {
  width: 192,
  height: 192,
  columns: ['rest', 'leftForward', 'pass', 'rightForward'],
  rows: ['north'],
} as const satisfies ThreeBranchesFrameGrid

export const THREE_BRANCHES_ASSET_MANIFEST = [
  {
    name: 'paperField',
    source: './source-art/paper-field-source.png',
    path: './assets/paper-field.png',
    width: 512,
    height: 512,
    tintable: false,
    consumer: 'paper tooth over the village ground',
  },
  {
    name: 'washCellA',
    source: './source-art/wash-cell-a-source.png',
    path: './assets/wash-cell-a.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'ground pigment pooling variant',
  },
  {
    name: 'washCellB',
    source: './source-art/wash-cell-b-source.png',
    path: './assets/wash-cell-b.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'ground pigment pooling variant',
  },
  {
    name: 'washCellC',
    source: './source-art/wash-cell-c-source.png',
    path: './assets/wash-cell-c.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'ground pigment pooling variant',
  },
  {
    name: 'roadBrushA',
    source: './source-art/road-brush-a-source.png',
    path: './assets/road-brush-a.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'raised-road dry-brush mark variant',
  },
  {
    name: 'roadBrushB',
    source: './source-art/road-brush-b-source.png',
    path: './assets/road-brush-b.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'raised-road dry-brush mark variant',
  },
  {
    name: 'roadBrushC',
    source: './source-art/road-brush-c-source.png',
    path: './assets/road-brush-c.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'raised-road dry-brush mark variant',
  },
  {
    name: 'furrowA',
    source: './source-art/furrow-a-source.png',
    path: './assets/furrow-a.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'field furrow variant',
  },
  {
    name: 'furrowB',
    source: './source-art/furrow-b-source.png',
    path: './assets/furrow-b.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'field furrow variant',
  },
  {
    name: 'furrowC',
    source: './source-art/furrow-c-source.png',
    path: './assets/furrow-c.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'field furrow variant',
  },
  {
    name: 'reedsA',
    source: './source-art/reeds-a-source.png',
    path: './assets/reeds-a.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'reed-flat mark variant',
  },
  {
    name: 'reedsB',
    source: './source-art/reeds-b-source.png',
    path: './assets/reeds-b.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'reed-flat mark variant',
  },
  {
    name: 'reedsC',
    source: './source-art/reeds-c-source.png',
    path: './assets/reeds-c.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'reed-flat mark variant',
  },
  {
    name: 'rippleA',
    source: './source-art/ripple-a-source.png',
    path: './assets/ripple-a.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'slack-water ripple variant',
  },
  {
    name: 'rippleB',
    source: './source-art/ripple-b-source.png',
    path: './assets/ripple-b.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'slack-water ripple variant',
  },
  {
    name: 'rippleC',
    source: './source-art/ripple-c-source.png',
    path: './assets/ripple-c.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'slack-water ripple variant',
  },
  {
    name: 'bankEdge',
    source: './source-art/bank-edge-source.png',
    path: './assets/bank-edge.png',
    width: 256,
    height: 64,
    tintable: true,
    consumer: 'water bank edge',
  },
  {
    name: 'roadEdge',
    source: './source-art/road-edge-source.png',
    path: './assets/road-edge.png',
    width: 256,
    height: 64,
    tintable: true,
    consumer: 'raised-road edge',
  },
  {
    name: 'pathEdge',
    source: './source-art/path-edge-source.png',
    path: './assets/path-edge.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'footpath edge',
  },
  {
    name: 'bridgePlanks',
    source: './source-art/bridge-planks-source.png',
    path: './assets/bridge-planks.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'bridge deck planks',
  },
  {
    name: 'wallBand',
    source: './source-art/wall-band-source.png',
    path: './assets/wall-band.png',
    width: 256,
    height: 64,
    tintable: true,
    consumer: 'open-building wall band',
  },
  {
    name: 'eaveBand',
    source: './source-art/eave-band-source.png',
    path: './assets/eave-band.png',
    width: 256,
    height: 64,
    tintable: true,
    consumer: 'open-building eave band',
  },
  {
    name: 'doorwayMark',
    source: './source-art/doorway-mark-source.png',
    path: './assets/doorway-mark.png',
    width: 128,
    height: 64,
    tintable: true,
    consumer: 'doorway-side threshold detail',
  },
  {
    name: 'floorHome',
    source: './source-art/floor-home-source.png',
    path: './assets/floor-home.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'home floor fill',
  },
  {
    name: 'floorInn',
    source: './source-art/floor-inn-source.png',
    path: './assets/floor-inn.png',
    width: 192,
    height: 128,
    tintable: true,
    consumer: 'inn floor fill',
  },
  {
    name: 'floorRepair',
    source: './source-art/floor-repair-source.png',
    path: './assets/floor-repair.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'repair shed floor fill',
  },
  {
    name: 'pineA',
    source: './source-art/pine-a-source.png',
    path: './assets/pine-a.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'red pine canopy variant',
  },
  {
    name: 'pineB',
    source: './source-art/pine-b-source.png',
    path: './assets/pine-b.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'red pine canopy variant',
  },
  {
    name: 'pineC',
    source: './source-art/pine-c-source.png',
    path: './assets/pine-c.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'red pine canopy variant',
  },
  {
    name: 'marketCrate',
    source: './source-art/market-crate-source.png',
    path: './assets/market-crate.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'market crate scenery',
  },
  {
    name: 'marketBarrel',
    source: './source-art/market-barrel-source.png',
    path: './assets/market-barrel.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'market barrel scenery',
  },
  {
    name: 'shrinePost',
    source: './source-art/shrine-post-source.png',
    path: './assets/shrine-post.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'roadside shrine roof post',
  },
  {
    name: 'stallOpen',
    source: './source-art/stall-open-source.png',
    path: './assets/stall-open.png',
    width: 256,
    height: 128,
    tintable: false,
    consumer: 'open market stall still',
  },
  {
    name: 'stallClosed',
    source: './source-art/stall-closed-source.png',
    path: './assets/stall-closed.png',
    width: 256,
    height: 128,
    tintable: false,
    consumer: 'closed market stall still',
  },
  {
    name: 'lanternLit',
    source: './source-art/lantern-lit-source.png',
    path: './assets/lantern-lit.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'lit lantern post still',
  },
  {
    name: 'lanternUnlit',
    source: './source-art/lantern-unlit-source.png',
    path: './assets/lantern-unlit.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'unlit lantern post still',
  },
  {
    name: 'benchOccupied',
    source: './source-art/bench-occupied-source.png',
    path: './assets/bench-occupied.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'occupied bench still',
  },
  {
    name: 'benchEmpty',
    source: './source-art/bench-empty-source.png',
    path: './assets/bench-empty.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'empty bench still',
  },
  {
    name: 'shrineTended',
    source: './source-art/shrine-tended-source.png',
    path: './assets/shrine-tended.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'tended roadside shrine still',
  },
  {
    name: 'shrineUntended',
    source: './source-art/shrine-untended-source.png',
    path: './assets/shrine-untended.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'untended roadside shrine still',
  },
  {
    name: 'noticeBoard',
    source: './source-art/notice-board-source.png',
    path: './assets/notice-board.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'notice board still',
  },
  {
    name: 'gardenTended',
    source: './source-art/garden-tended-source.png',
    path: './assets/garden-tended.png',
    width: 256,
    height: 128,
    tintable: false,
    consumer: 'tended garden plot still',
  },
  {
    name: 'gardenOvergrown',
    source: './source-art/garden-overgrown-source.png',
    path: './assets/garden-overgrown.png',
    width: 256,
    height: 128,
    tintable: false,
    consumer: 'overgrown garden plot still',
  },
  {
    name: 'hearthLit',
    source: './source-art/hearth-lit-source.png',
    path: './assets/hearth-lit.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'lit inn hearth still',
  },
  {
    name: 'hearthUnlit',
    source: './source-art/hearth-unlit-source.png',
    path: './assets/hearth-unlit.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'unlit inn hearth still',
  },
  {
    name: 'repairBenchBusy',
    source: './source-art/repair-bench-busy-source.png',
    path: './assets/repair-bench-busy.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'busy repair bench still',
  },
  {
    name: 'repairBenchIdle',
    source: './source-art/repair-bench-idle-source.png',
    path: './assets/repair-bench-idle.png',
    width: 192,
    height: 128,
    tintable: false,
    consumer: 'idle repair bench still',
  },
  {
    name: 'pumpFlowing',
    source: './source-art/pump-flowing-source.png',
    path: './assets/pump-flowing.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'flowing well pump still',
  },
  {
    name: 'pumpIdle',
    source: './source-art/pump-idle-source.png',
    path: './assets/pump-idle.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'idle well pump still',
  },
  {
    name: 'bellRinging',
    source: './source-art/bell-ringing-source.png',
    path: './assets/bell-ringing.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'ringing beacon bell still',
  },
  {
    name: 'bellSilent',
    source: './source-art/bell-silent-source.png',
    path: './assets/bell-silent.png',
    width: 128,
    height: 128,
    tintable: false,
    consumer: 'silent beacon bell still',
  },
  {
    name: 'shadowOval',
    source: './source-art/shadow-oval-source.png',
    path: './assets/shadow-oval.png',
    width: 64,
    height: 64,
    tintable: true,
    consumer: 'character shadow',
  },
  {
    name: 'directionMark',
    source: './source-art/direction-mark-source.png',
    path: './assets/direction-mark.png',
    width: 64,
    height: 64,
    tintable: true,
    consumer: 'exact character heading mark',
  },
  {
    name: 'villagerHeadA',
    source: './source-art/villager-head-a-source.png',
    path: './assets/villager-head-a.png',
    width: 192,
    height: 192,
    tintable: false,
    consumer: 'rotatable tied-hair villager head',
  },
  {
    name: 'villagerHeadB',
    source: './source-art/villager-head-b-source.png',
    path: './assets/villager-head-b.png',
    width: 192,
    height: 192,
    tintable: false,
    consumer: 'rotatable headscarf villager head',
  },
  {
    name: 'villagerHeadC',
    source: './source-art/villager-head-c-source.png',
    path: './assets/villager-head-c.png',
    width: 192,
    height: 192,
    tintable: false,
    consumer: 'rotatable reed-cap villager head',
  },
  {
    name: 'visitorHead',
    source: './source-art/visitor-head-source.png',
    path: './assets/visitor-head.png',
    width: 192,
    height: 192,
    tintable: false,
    consumer: 'rotatable visitor hood with cinnabar knot',
  },
  {
    name: 'characterHands',
    source: './source-art/character-hands-source.png',
    path: './assets/character-hands.png',
    width: 768,
    height: 192,
    tintable: false,
    consumer: 'shared rotatable walking hands',
    frames: CHARACTER_HAND_FRAMES,
  },
  {
    name: 'glow',
    source: './source-art/glow-source.png',
    path: './assets/glow.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'post-grade lantern and hearth warmth',
  },
  {
    name: 'flame',
    source: './source-art/flame-source.png',
    path: './assets/flame.png',
    width: 64,
    height: 64,
    tintable: true,
    consumer: 'lit hearth animation',
  },
  {
    name: 'smoke',
    source: './source-art/smoke-source.png',
    path: './assets/smoke.png',
    width: 64,
    height: 64,
    tintable: true,
    consumer: 'tended shrine incense',
  },
  {
    name: 'waterStream',
    source: './source-art/water-stream-source.png',
    path: './assets/water-stream.png',
    width: 64,
    height: 128,
    tintable: true,
    consumer: 'flowing well pump animation',
  },
  {
    name: 'bellLines',
    source: './source-art/bell-lines-source.png',
    path: './assets/bell-lines.png',
    width: 128,
    height: 128,
    tintable: true,
    consumer: 'ringing beacon bell motion marks',
  },
  {
    name: 'craneA',
    source: './source-art/crane-a-source.png',
    path: './assets/crane-a.png',
    width: 192,
    height: 128,
    tintable: true,
    consumer: 'white crane ambience pose',
  },
  {
    name: 'craneB',
    source: './source-art/crane-b-source.png',
    path: './assets/crane-b.png',
    width: 192,
    height: 128,
    tintable: true,
    consumer: 'white crane ambience pose',
  },
] as const satisfies readonly ThreeBranchesAssetDraft[]

type ThreeBranchesAssetDraft = Omit<ThreeBranchesAsset, 'name'> & { name: string }
export type ThreeBranchesAssetName = (typeof THREE_BRANCHES_ASSET_MANIFEST)[number]['name']
