"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/. Do not edit by hand. The students'
agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete public
registry metadata used by the browser relay and the injected harness entry.

This template targets Flappy Bird. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import EnvironmentMeta

from .flappy_bird import default_action, extract_overlay, make_env

ENV_ID = "flappy_bird"
PLAYER_SLOT = "player_0"
META = EnvironmentMeta(
    **{
        "env_id": "flappy_bird",
        "display_name": "Flappy Bird",
        "description": (
            "A Flappy Bird style single-agent game: tap to flap and steer the bird through the gaps "
            "between pipes. Brought in through the single-agent compatibility wrapper."
        ),
        "min_slots": 1,
        "max_slots": 1,
        "human_slots": ("player_0",),
        "human_timeout_ms": None,
        "recommended_episode_ticks": 1000,
        "pace_interval_ms": 50,
        "step_limit_ms": 1000,
        "episode_limit_ms": 120000,
        "messaging": False,
        "message_cap": None,
        "llm": False,
        "renderer": "flappy-bird",
        "seat_order_matters": False,
        "view_interval_ms": None,
        "live_interval_ms": None,
    }
)

__all__ = [
    "make_env",
    "extract_overlay",
    "default_action",
    "ENV_ID",
    "PLAYER_SLOT",
    "META",
]
