"""Synced Flappy Bird environment for local development.

GENERATED by scripts/generate.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally not synced; locally you build the env directly:

    from sandbox_env.flappy_bird.env import make_env
"""

from .env import NOOP_ACTION, make_env
from .overlay import extract_overlay

__all__ = ["make_env", "extract_overlay", "NOOP_ACTION"]
