/**
 * The single source of truth for the backend's stored data.
 *
 * The Kysely table interfaces below are the schema; every other stored-data type derives from
 * them through Kysely's type-level helpers (`Selectable` and friends), so there is no parallel
 * hand-maintained type set to drift. The orchestrator, the HTTP layer, and tests pass around
 * the derived domain types. Engine portability comes from Kysely itself: a different database
 * is a different dialect wired in at construction (see `sqlite.ts`), not a second schema.
 *
 * Later stages add their tables, unions, and derived types (submissions, iterations, ratings)
 * to this file.
 */
import type { Insertable, Selectable, Updateable } from 'kysely'

/** Whether a session is human-controlled or runs the built-in scripted agent. */
export type SessionMode = 'human' | 'scripted'

/** A session's lifecycle state. */
export type SessionStatus = 'starting' | 'running' | 'ended'

/**
 * Why a session ended. The first three come from the container's `result` envelope; the rest
 * are orchestrator-side outcomes (a client stop, the idle window, the wall-clock backstop, a
 * quota kill, or a crash).
 */
export type TerminationReason =
  | 'terminated'
  | 'truncated'
  | 'episode_limit'
  | 'stopped'
  | 'idle_timeout'
  | 'time_limit'
  | 'oom_killed'
  | 'error'

/** The `sessions` table: one row per launched session. */
export interface SessionsTable {
  /** Text id generated by the backend at start. */
  id: string
  user_id: string
  env_id: string
  mode: SessionMode
  status: SessionStatus
  /** Null until the session ends. */
  termination_reason: TerminationReason | null
  recording_id: string | null
  /** ISO-8601 UTC timestamps. */
  created_at: string
  ended_at: string | null
}

/**
 * The `recordings` table: one row per produced recording, its retention metadata. The directory
 * on the volume is the recording itself; this row carries who owns it, when it was made, and
 * whether it is pinned (exempt from eviction). Written by the session finalize routine and
 * backfilled from {@link SessionsTable} for pre-Stage-4 recordings; a volume directory with no
 * row after backfill is foreign debris — listed header-only, never evicted.
 */
export interface RecordingsTable {
  /** The recording id, matching the directory name on the volume. */
  id: string
  user_id: string
  env_id: string
  /** ISO-8601 UTC timestamp, the moment the recording was produced. */
  created_at: string
  /** SQLite has no boolean: 0 or 1, defaulting to 0 (unpinned). */
  pinned: number
}

/**
 * An iteration's lifecycle state. Only `open` is exercised this stage; Stage 6 adds the close
 * controls and historical views that make `closed` meaningful.
 */
export type IterationStatus = 'open' | 'closed'

/** Where a submission's code came from: a pinned git repository or a dev-only local folder. */
export type SubmissionSourceKind = 'git' | 'local'

/**
 * A submission's terminal rollup status, the small set the watch picker and active-submission
 * rule filter on. `resolve` and `static` stage failures both roll up to `static_failed`
 * (reachability/ref-resolution is grouped under the spec's static-checks layer); `build` rolls
 * up to `build_failed` and `load` to `load_failed`. Do not widen this set to "clarify" a stage:
 * the granular per-stage view lives in {@link SubmissionChecksTable}, not here.
 */
export type SubmissionStatus =
  | 'pending'
  | 'static_failed'
  | 'load_failed'
  | 'build_failed'
  | 'ready'

/** The ordered validation-pipeline gates, in run order. */
export type SubmissionStage = 'resolve' | 'static' | 'build' | 'load'

/** A per-stage validation check's state. */
export type CheckStatus = 'running' | 'passed' | 'failed' | 'skipped'

/**
 * The `iterations` table: one row per environment's competition iteration. This stage seeds a
 * single open iteration per environment so submissions have an identity boundary and a pinned
 * dependency-set version; Stage 6 replaces the seed with the operator CLI and full configuration,
 * extending this column set rather than rewriting it.
 */
export interface IterationsTable {
  /** Text id generated by the backend. */
  id: string
  env_id: string
  /** The template dependency-set version this iteration pins; every submission runs on it. */
  deps_version: number
  status: IterationStatus
  /** ISO-8601 UTC timestamp. */
  created_at: string
}

/**
 * The `submissions` table: one row per submitted agent. The row is created `pending` before
 * source resolution so an unreachable repo or non-resolving ref is still stored (as
 * `static_failed`). The source resolver fills `commit_sha` when git pinning succeeds, and the
 * build pipeline drives `status`/`reason`. One active (`superseded_at IS NULL`) submission per
 * `(iteration_id, user_id)` is enforced by a partial unique index; resubmission supersedes the
 * prior row and inserts a new one, preserving history.
 */
export interface SubmissionsTable {
  /** Text id generated by the backend. */
  id: string
  iteration_id: string
  /** Denormalized for lookups; derivable from the iteration. */
  env_id: string
  /** The resolved identity from the Stage 4 seam (the GitHub username once OAuth replaces it). */
  user_id: string
  source_kind: SubmissionSourceKind
  /** The clean repo URL for git sources (never tokenized); null for local. */
  repo_url: string | null
  /** The pinned exact SHA after git resolution; null for local and for git rows that fail before pinning. */
  commit_sha: string | null
  /** The server-side folder path for local sources; null for git. */
  local_path: string | null
  /** The branch/tag/commit the participant supplied; null when they gave none and we took the default-branch head. */
  ref: string | null
  status: SubmissionStatus
  /** Null until a layer rejects; the specific owner-visible message, a copy of the terminal stage's detail. */
  reason: string | null
  /** ISO-8601 UTC timestamp. */
  created_at: string
  /** Null for the active row; stamped when a later submission supersedes this one. */
  superseded_at: string | null
}

/**
 * The `session_submissions` table: which submitted agent ran in which session slot. Keyed by
 * `(session_id, slot_id)`, the slot within a session is the natural key, so there is no surrogate
 * id. Stage 5 writes one row per submitted-agent watch session (`player_0` for Flappy Bird); Stage
 * 8 extends it to one row per submitted slot in multi-agent sessions.
 */
export interface SessionSubmissionsTable {
  session_id: string
  submission_id: string
  slot_id: string
  /** ISO-8601 UTC timestamp. */
  created_at: string
}

/**
 * The `submission_checks` table: the ordered per-stage validation log the form polls and the
 * profile shows. One row per pipeline stage the worker reaches: `running` when the stage starts,
 * then the outcome when it finishes. Stages after a failure are never reached and are simply
 * absent (rendered as not-yet-run). A unique `(submission_id, stage)` index keeps a stage to a
 * single row even when startup re-enqueues a pending submission. This log does not replace the
 * submission's own `status`/`reason` rollup; it is the granular "where did it go wrong" view.
 */
export interface SubmissionChecksTable {
  /** Text id generated by the backend. */
  id: string
  submission_id: string
  stage: SubmissionStage
  status: CheckStatus
  /** Null until there is an owner-facing message: the typed rejection reason or captured error text. */
  detail: string | null
  /** ISO-8601 UTC timestamp. */
  started_at: string
  /** Null while a stage is still `running`. */
  ended_at: string | null
}

/** The database schema: table names mapped to their row interfaces. */
export interface Database {
  sessions: SessionsTable
  recordings: RecordingsTable
  iterations: IterationsTable
  submissions: SubmissionsTable
  session_submissions: SessionSubmissionsTable
  submission_checks: SubmissionChecksTable
}

/** A session row as read back from the database. */
export type Session = Selectable<SessionsTable>

/** A session row as inserted. */
export type NewSession = Insertable<SessionsTable>

/** A partial session update. */
export type SessionUpdate = Updateable<SessionsTable>

/** A recording row as read back from the database. */
export type Recording = Selectable<RecordingsTable>

/** A recording row as inserted. */
export type NewRecording = Insertable<RecordingsTable>

/** An iteration row as read back from the database. */
export type Iteration = Selectable<IterationsTable>

/** A submission row as read back from the database. */
export type Submission = Selectable<SubmissionsTable>

/** A submission row as inserted. */
export type NewSubmission = Insertable<SubmissionsTable>

/** A partial submission update. */
export type SubmissionUpdate = Updateable<SubmissionsTable>

/** A session-submission link row as read back from the database. */
export type SessionSubmission = Selectable<SessionSubmissionsTable>

/** A submission validation-check row as read back from the database. */
export type SubmissionCheck = Selectable<SubmissionChecksTable>
