/**
 * The single source of truth for the backend's stored data.
 *
 * The Kysely table interfaces below are the schema; every other stored-data type derives from
 * them through Kysely's type-level helpers (`Selectable` and friends), so there is no parallel
 * hand-maintained type set to drift. The orchestrator, the HTTP layer, and tests pass around
 * the derived domain types. Engine portability comes from Kysely itself: a different database
 * is a different dialect wired in at construction (see `sqlite.ts`), not a second schema.
 *
 * Later stages add their tables, unions, and derived types (submissions, iterations, ratings)
 * to this file.
 */
import type { Insertable, Selectable, Updateable } from 'kysely'

/** Whether a session is human-controlled or runs the built-in scripted agent. */
export type SessionMode = 'human' | 'scripted'

/** A session's lifecycle state. */
export type SessionStatus = 'starting' | 'running' | 'ended'

/**
 * Why a session ended. The first three come from the container's `result` envelope; the rest
 * are orchestrator-side outcomes (a client stop, the idle window, the wall-clock backstop, a
 * quota kill, or a crash).
 */
export type TerminationReason =
  | 'terminated'
  | 'truncated'
  | 'episode_limit'
  | 'stopped'
  | 'idle_timeout'
  | 'time_limit'
  | 'oom_killed'
  | 'error'

/** The `sessions` table: one row per launched session. */
export interface SessionsTable {
  /** Text id generated by the backend at start. */
  id: string
  user_id: string
  env_id: string
  mode: SessionMode
  status: SessionStatus
  /** Null until the session ends. */
  termination_reason: TerminationReason | null
  recording_id: string | null
  /** ISO-8601 UTC timestamps. */
  created_at: string
  ended_at: string | null
}

/** The database schema: table names mapped to their row interfaces. */
export interface Database {
  sessions: SessionsTable
}

/** A session row as read back from the database. */
export type Session = Selectable<SessionsTable>

/** A session row as inserted. */
export type NewSession = Insertable<SessionsTable>

/** A partial session update. */
export type SessionUpdate = Updateable<SessionsTable>
