/**
 * The single source of truth for the backend's stored data.
 *
 * The Kysely table interfaces below are the schema; every other stored-data type derives from
 * them through Kysely's type-level helpers (`Selectable` and friends), so there is no parallel
 * hand-maintained type set to drift. The orchestrator, the HTTP layer, and tests pass around
 * the derived domain types. Engine portability comes from Kysely itself: a different database
 * is a different dialect wired in at construction (see `sqlite.ts`), not a second schema.
 *
 * Later stages add their tables, unions, and derived types (submissions, seasons, ratings)
 * to this file.
 */
import type { Insertable, Selectable, Updateable } from 'kysely'

/** Whether a session is human-controlled or runs the built-in scripted agent. */
export type SessionMode = 'human' | 'scripted'

/** A session's lifecycle state. */
export type SessionStatus = 'starting' | 'running' | 'ended'

/**
 * Why a session ended. The first three come from the container's `result` envelope; the rest
 * are orchestrator-side outcomes (a client stop, the idle window, the wall-clock backstop, a
 * quota kill, or a crash).
 */
export type TerminationReason =
  | 'terminated'
  | 'truncated'
  | 'episode_limit'
  | 'stopped'
  | 'idle_timeout'
  | 'time_limit'
  | 'oom_killed'
  | 'error'

/** The `sessions` table: one row per launched session. */
export interface SessionsTable {
  /** Text id generated by the backend at start. */
  id: string
  user_id: string
  env_id: string
  mode: SessionMode
  status: SessionStatus
  /** Null until the session ends. */
  termination_reason: TerminationReason | null
  recording_id: string | null
  /**
   * The season this session competes in, the key ratings later attach to. Null for old (pre-Stage
   * 6) rows and for any session with no competition boundary; a null-season session can never be
   * rated. Stage 6 writes it for every new rateable watch/play session from an explicit target.
   */
  season_id: string | null
  /** ISO-8601 UTC timestamps. */
  created_at: string
  ended_at: string | null
}

/**
 * The `recordings` table: one row per produced recording, its retention metadata. The directory
 * on the volume is the recording itself; this row carries who owns it, when it was made, and
 * whether it is pinned (exempt from eviction). Written by the session finalize routine and
 * backfilled from {@link SessionsTable} for pre-Stage-4 recordings; a volume directory with no
 * row after backfill is foreign debris — listed header-only, never evicted.
 */
export interface RecordingsTable {
  /** The recording id, matching the directory name on the volume. */
  id: string
  user_id: string
  env_id: string
  /** ISO-8601 UTC timestamp, the moment the recording was produced. */
  created_at: string
  /** SQLite has no boolean: 0 or 1, defaulting to 0 (unpinned). */
  pinned: number
}

/**
 * A public gate's open/closed state. The submission window and the public-play window are each one of
 * these, modeled as independent columns because they gate different surfaces and move independently.
 */
export type WindowStatus = 'open' | 'closed'

/**
 * The Stage 5 name for the submission window. Retained as an alias of {@link WindowStatus} so existing
 * imports keep resolving; the column is `submission_status` now that "open" is ambiguous across the
 * two windows.
 */
export type SeasonStatus = WindowStatus

/**
 * Whether a season's results (its boards and history) are visible outside the operator console.
 * They stay operator-only until released, independent of either window — play can be open on an
 * `unreleased` season.
 */
export type ReleaseStatus = 'unreleased' | 'released'

/** One automated workflow execution's lifecycle state. */
export type RunStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'

/** One scheduled match's lifecycle state. */
export type GameStatus = 'pending' | 'running' | 'completed' | 'failed' | 'timed_out' | 'cancelled'

/** Which kind of agent occupied a seat: a participant submission, or the built-in scripted baseline. */
export type AgentKind = 'submission' | 'builtin-naive'

/**
 * The one agent-identity shape this stage stores or returns everywhere a seat, result, placement,
 * rating, or board row names an agent. Tables that filter or group on it store the three concrete
 * columns below ({@link AgentColumns}) rather than this opaque JSON; JSON payloads (scheduled slots,
 * board/rating responses) carry it directly. For `builtin-naive` both id columns are null; for a
 * submitted agent both are required.
 */
export type AgentRef =
  | { kind: 'submission'; submission_id: string; user_id: string }
  | { kind: 'builtin-naive' }

/** The concrete column triple every agent-keyed table stores, derived from an {@link AgentRef}. */
export interface AgentColumns {
  agent_kind: AgentKind
  agent_submission_id: string | null
  agent_user_id: string | null
}

/** Where a submission's code came from: a pinned git repository or a dev-only local folder. */
export type SubmissionSourceKind = 'git' | 'local'

/**
 * A submission's terminal rollup status, the small set the watch picker and active-submission
 * rule filter on. `resolve` and `static` stage failures both roll up to `static_failed`
 * (reachability/ref-resolution is grouped under the spec's static-checks layer); `build` rolls
 * up to `build_failed` and `load` to `load_failed`. Do not widen this set to "clarify" a stage:
 * the granular per-stage view lives in {@link SubmissionChecksTable}, not here.
 */
export type SubmissionStatus =
  | 'pending'
  | 'static_failed'
  | 'load_failed'
  | 'build_failed'
  | 'ready'

/** The ordered validation-pipeline gates, in run order. */
export type SubmissionStage = 'resolve' | 'static' | 'build' | 'load'

/** A per-stage validation check's state. */
export type CheckStatus = 'running' | 'passed' | 'failed' | 'skipped'

/**
 * The `seasons` table: one row per environment's competition season. Stage 6 grows the minimal
 * Stage 5 row into full per-season configuration. The submission window, public-play window, and
 * release status are three independent gates, modeled as separate columns; the pinned dependency-set
 * version is no longer its own column but folds into the validated {@link SeasonConfig} `config`
 * document, so a run's `config_snapshot` is the single frozen record of what governed it.
 */
export interface SeasonsTable {
  /** Text id generated by the backend. */
  id: string
  env_id: string
  /**
   * Whether the submission form accepts agents (the Stage 5 `status`, renamed). A partial unique
   * index keeps at most one `open` season per environment.
   */
  submission_status: WindowStatus
  /**
   * Whether ordinary allowlisted users can start public watch/play sessions and write ratings against
   * this season. Independent of release status; a partial unique index keeps at most one `open`
   * season per environment as the default public-play target.
   */
  play_status: WindowStatus
  /** Whether the season's results are shown outside the operator console. */
  release_status: ReleaseStatus
  /** An operator-facing name ("Week 3", "Final round"); null when unset. */
  label: string | null
  /** The validated {@link SeasonConfig} document as JSON text (includes the pinned `deps_version`). */
  config: string
  /**
   * The operator's season-wide rating prompt shown to human raters for every agent. Null or empty
   * means none. Editable at any point in the season's life — it never affects workflow execution —
   * so it is its own always-editable column rather than part of the force-confirmed `config`.
   */
  rating_prompt: string | null
  /** ISO-8601 UTC timestamp. */
  created_at: string
  /** Stamped on first release, for history ordering; null while unreleased. */
  released_at: string | null
}

/**
 * The `season_runs` table: one row per automated workflow execution. The workflow can run more
 * than once per season (a re-run is a new row), and the board always points at the latest
 * completed one. The run freezes everything that governs it — the validated config (with `deps_version`)
 * and the eligible submitted-agent roster — at trigger time, so editing the season or resubmitting
 * afterward cannot change what the run executes.
 */
export interface SeasonRunsTable {
  /** Text id generated by the backend. */
  id: string
  season_id: string
  /** The operator identity that triggered the run. */
  requested_by: string
  /** The validated {@link SeasonConfig} JSON, copied from the season when the run is created. */
  config_snapshot: string
  /** JSON array of the active `ready` submitted-agent {@link AgentRef}s eligible at trigger time. */
  submission_snapshot: string
  status: RunStatus
  /** ISO-8601 UTC timestamp the run was created/triggered. */
  started_at: string
  /** Null while running; stamped when the run reaches a terminal status. */
  ended_at: string | null
  /** Null unless a run-level failure occurred. */
  error: string | null
}

/**
 * The `season_run_games` table: one row per scheduled match, written from the pure scheduler before
 * the runner starts. The runner only advances `status` and fills `recording_id`/results; the board
 * aggregates these. `game_index` is the deterministic schedule index within the run and the tie-breaker
 * for representative-replay selection.
 */
export interface SeasonRunGamesTable {
  /** Text id generated by the backend. */
  id: string
  run_id: string
  /** Which `config_snapshot.matches` entry produced this game. */
  match_index: number
  /** The deterministic schedule index within the run. */
  game_index: number
  seed: number
  /** JSON array of resolved {@link AgentRef} values, one per seat. */
  slots: string
  status: GameStatus
  /** FK into the Stage 4 recordings, set when the run records; the board's per-row replay link. */
  recording_id: string | null
  /** Null until the game starts running. */
  started_at: string | null
  ended_at: string | null
  error: string | null
}

/**
 * The `game_results` table: one row per participating seat per game, when a result can be attributed
 * to a specific agent. Normalized so the board can aggregate per agent without averaging per-game
 * means. An infrastructure failure (a container that never starts, an unreadable recording) marks the
 * game failed but invents no row here.
 */
export interface GameResultsTable {
  /** Text id generated by the backend. */
  id: string
  game_id: string
  slot_index: number
  agent_kind: AgentKind
  agent_submission_id: string | null
  agent_user_id: string | null
  /** The normalized higher-is-better leaderboard score from the recording. */
  episode_score: number
  /** Sum of `decision_ms + learn_ms` over the seat's ticks (`learn_ms` treated as zero where absent). */
  agent_compute_ms_total: number
  /** The number of ticks that carried this seat's timing and contributed to the total. */
  acted_tick_count: number
  /** SQLite boolean (0/1): the agent crashed or timed out but a score row still exists. */
  failed: number
  failure_reason: string | null
}

/**
 * The `automated_placements` table: the per-agent placement snapshot profiles and history read, not
 * full board rows. Rewritten when a new completed run supersedes the prior one. Submitted-agent rows
 * are unique on `(season_id, agent_kind, agent_submission_id)`; the Naive row (null submission id)
 * is kept unique by a second partial index on `(season_id, agent_kind)`.
 */
export interface AutomatedPlacementsTable {
  /** Text id generated by the backend. */
  id: string
  season_id: string
  env_id: string
  run_id: string
  rank: number
  agent_kind: AgentKind
  agent_submission_id: string | null
  agent_user_id: string | null
  mean_score: number
  /** Null/blank when the contributing tick count was zero. */
  mean_agent_compute_ms: number | null
  failure_count: number
  recording_id: string | null
  /** ISO-8601 UTC timestamp. */
  created_at: string
}

/**
 * The `ratings` table: one 1-5 human rating per user per agent per season (re-rating is an upsert).
 * A unique index enforces the one-effective-rating rule; a second partial index covers the Naive row,
 * whose null `agent_submission_id` SQLite would otherwise treat as always-distinct. Ratings of a
 * user's own submitted agent are rejected at the storage/route layer and never inserted.
 */
export interface RatingsTable {
  /** Text id generated by the backend. */
  id: string
  season_id: string
  /** Denormalized for lookups; derivable from the season. */
  env_id: string
  /** The resolved rater identity from the Stage 4 seam. */
  rater_user_id: string
  agent_kind: AgentKind
  agent_submission_id: string | null
  agent_user_id: string | null
  /** Integer 1-5. */
  score: number
  /** ISO-8601 UTC timestamps. */
  created_at: string
  updated_at: string
}

/**
 * The `agent_rating_prompts` table: the agent author's own statement of what to evaluate, the second
 * prompt a rater sees. Settable and editable after submission, so it is not part of the pinned
 * submission artifact and lives here keyed per author per season, surviving resubmission within the
 * season. Only submitted agents have authors; the Naive baseline never has a row.
 */
export interface AgentRatingPromptsTable {
  season_id: string
  /** Denormalized for lookups. */
  env_id: string
  /** The author's resolved identity. */
  user_id: string
  /** Length-capped prompt text. */
  prompt: string
  /** ISO-8601 UTC timestamp. */
  updated_at: string
}

/**
 * The `submissions` table: one row per submitted agent. The row is created `pending` before
 * source resolution so an unreachable repo or non-resolving ref is still stored (as
 * `static_failed`). The source resolver fills `commit_sha` when git pinning succeeds, and the
 * build pipeline drives `status`/`reason`. One active (`superseded_at IS NULL`) submission per
 * `(season_id, user_id)` is enforced by a partial unique index; resubmission supersedes the
 * prior row and inserts a new one, preserving history.
 */
export interface SubmissionsTable {
  /** Text id generated by the backend. */
  id: string
  season_id: string
  /** Denormalized for lookups; derivable from the season. */
  env_id: string
  /** The resolved identity from the Stage 4 seam (the GitHub username once OAuth replaces it). */
  user_id: string
  source_kind: SubmissionSourceKind
  /** The clean repo URL for git sources (never tokenized); null for local. */
  repo_url: string | null
  /** The pinned exact SHA after git resolution; null for local and for git rows that fail before pinning. */
  commit_sha: string | null
  /** The server-side folder path for local sources; null for git. */
  local_path: string | null
  /** The branch/tag/commit the participant supplied; null when they gave none and we took the default-branch head. */
  ref: string | null
  status: SubmissionStatus
  /** Null until a layer rejects; the specific owner-visible message, a copy of the terminal stage's detail. */
  reason: string | null
  /** ISO-8601 UTC timestamp. */
  created_at: string
  /** Null for the active row; stamped when a later submission supersedes this one. */
  superseded_at: string | null
}

/**
 * The `session_submissions` table: which submitted agent ran in which session slot. Keyed by
 * `(session_id, slot_id)`, the slot within a session is the natural key, so there is no surrogate
 * id. Stage 5 writes one row per submitted-agent watch session (`player_0` for Flappy Bird); Stage
 * 8 extends it to one row per submitted slot in multi-agent sessions.
 */
export interface SessionSubmissionsTable {
  session_id: string
  submission_id: string
  slot_id: string
  /** ISO-8601 UTC timestamp. */
  created_at: string
}

/**
 * The `submission_checks` table: the ordered per-stage validation log the form polls and the
 * profile shows. One row per pipeline stage the worker reaches: `running` when the stage starts,
 * then the outcome when it finishes. Stages after a failure are never reached and are simply
 * absent (rendered as not-yet-run). A unique `(submission_id, stage)` index keeps a stage to a
 * single row even when startup re-enqueues a pending submission. This log does not replace the
 * submission's own `status`/`reason` rollup; it is the granular "where did it go wrong" view.
 */
export interface SubmissionChecksTable {
  /** Text id generated by the backend. */
  id: string
  submission_id: string
  stage: SubmissionStage
  status: CheckStatus
  /** Null until there is an owner-facing message: the typed rejection reason or captured error text. */
  detail: string | null
  /** ISO-8601 UTC timestamp. */
  started_at: string
  /** Null while a stage is still `running`. */
  ended_at: string | null
}

/** The database schema: table names mapped to their row interfaces. */
export interface Database {
  sessions: SessionsTable
  recordings: RecordingsTable
  seasons: SeasonsTable
  submissions: SubmissionsTable
  session_submissions: SessionSubmissionsTable
  submission_checks: SubmissionChecksTable
  season_runs: SeasonRunsTable
  season_run_games: SeasonRunGamesTable
  game_results: GameResultsTable
  automated_placements: AutomatedPlacementsTable
  ratings: RatingsTable
  agent_rating_prompts: AgentRatingPromptsTable
}

/** A session row as read back from the database. */
export type Session = Selectable<SessionsTable>

/** A session row as inserted. */
export type NewSession = Insertable<SessionsTable>

/** A partial session update. */
export type SessionUpdate = Updateable<SessionsTable>

/** A recording row as read back from the database. */
export type Recording = Selectable<RecordingsTable>

/** A recording row as inserted. */
export type NewRecording = Insertable<RecordingsTable>

/** A season row as read back from the database. */
export type Season = Selectable<SeasonsTable>

/** A partial season update. */
export type SeasonUpdate = Updateable<SeasonsTable>

/** A season-run row as read back from the database. */
export type SeasonRun = Selectable<SeasonRunsTable>

/** A scheduled-match row as read back from the database. */
export type SeasonRunGame = Selectable<SeasonRunGamesTable>

/** A per-seat game-result row as read back from the database. */
export type GameResult = Selectable<GameResultsTable>

/** An automated-placement row as read back from the database. */
export type AutomatedPlacement = Selectable<AutomatedPlacementsTable>

/** A rating row as read back from the database. */
export type Rating = Selectable<RatingsTable>

/** An agent-author rating-prompt row as read back from the database. */
export type AgentRatingPrompt = Selectable<AgentRatingPromptsTable>

/** A submission row as read back from the database. */
export type Submission = Selectable<SubmissionsTable>

/** A submission row as inserted. */
export type NewSubmission = Insertable<SubmissionsTable>

/** A partial submission update. */
export type SubmissionUpdate = Updateable<SubmissionsTable>

/** A session-submission link row as read back from the database. */
export type SessionSubmission = Selectable<SessionSubmissionsTable>

/** A submission validation-check row as read back from the database. */
export type SubmissionCheck = Selectable<SubmissionChecksTable>
