"""Write generated template pieces into a composed student kit.

The hand-authored base and environment layers stay in the repository. Composition writes the
environment package, relocatable harness, and shared helper modules into a fresh build directory.
"""

from __future__ import annotations

import json
import shutil
import textwrap
from pathlib import Path

from _paths import ENVIRONMENT_PACKAGES_DIR, REPO_ROOT, TEMPLATE_BASE_MODULES, TemplateEnvironmentSpec


def _render_metadata_mapping(metadata: dict[str, object]) -> str:
    """Render registry metadata in the same shape Ruff would format it."""
    lines = ["    **{"]
    for key, value in metadata.items():
        prefix = f'        "{key}": '
        if isinstance(value, str) and len(prefix) + len(json.dumps(value)) > 110:
            chunks = textwrap.wrap(value, width=88, break_long_words=False, break_on_hyphens=False)
            lines.append(f"{prefix}(")
            for index, chunk in enumerate(chunks):
                suffix = " " if index < len(chunks) - 1 else ""
                lines.append(f"            {json.dumps(chunk + suffix)}")
            lines.append("        ),")
        elif isinstance(value, str):
            lines.append(f"{prefix}{json.dumps(value)},")
        elif isinstance(value, tuple):
            items = ", ".join(json.dumps(item) for item in value)
            trailing_comma = "," if len(value) == 1 else ""
            lines.append(f"{prefix}({items}{trailing_comma}),")
        else:
            lines.append(f"{prefix}{value!r},")
    lines.append("    }")
    return "\n".join(lines)


def _render_sandbox_init(env_id: str, spec: TemplateEnvironmentSpec, meta: object) -> str:
    """Render the uniform ``sandbox/env/__init__.py`` surface."""
    from game_sandbox_harness.environment import EnvironmentMeta

    if not isinstance(meta, EnvironmentMeta):
        raise TypeError(f"expected EnvironmentMeta for {env_id!r}, got {type(meta).__name__}")
    metadata = meta.to_json()
    metadata["human_slots"] = tuple(metadata["human_slots"])
    metadata_text = _render_metadata_mapping(metadata)
    surface_import = f"from .{spec.inner_package} import {spec.default_action}, extract_overlay, make_env"
    return f'''\
# GAME-SANDBOX-GENERATED-ENV: scripts/compose.py
"""Composed copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/compose.py from environments/{env_id}/. Do not edit by hand. The
students' agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete
public registry metadata used by the browser relay and the injected harness entry.

This template targets {spec.display_name}. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import EnvironmentMeta

{surface_import}

ENV_ID = "{env_id}"
PLAYER_SLOT = "{spec.player_slot}"
META = EnvironmentMeta(
{metadata_text}
)

__all__ = [
    "make_env",
    "extract_overlay",
    "{spec.default_action}",
    "ENV_ID",
    "PLAYER_SLOT",
    "META",
]
'''


def _render_inner_init(spec: TemplateEnvironmentSpec) -> str:
    """Render the re-exporting inner environment package ``__init__.py``."""
    return f'''\
"""Composed {spec.display_name} environment for local development.

GENERATED by scripts/compose.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally omitted; locally you build the env directly:

    from sandbox.env import make_env
"""

from .env import {spec.default_action}, make_env
from .overlay import extract_overlay

__all__ = ["make_env", "extract_overlay", "{spec.default_action}"]
'''


def write_env_package(env_id: str, spec: TemplateEnvironmentSpec, meta: object, dest: Path) -> None:
    """Write one environment's import-self-contained modules under ``dest``."""
    dest.mkdir(parents=True, exist_ok=True)
    for relative in spec.modules:
        path = dest / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ENVIRONMENT_PACKAGES_DIR / relative, path)

    inits = {
        "__init__.py": _render_sandbox_init(env_id, spec, meta),
        f"{spec.inner_package}/__init__.py": _render_inner_init(spec),
    }
    for relative, text in inits.items():
        path = dest / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")


def write_harness(dest: Path) -> None:
    """Copy the relocatable harness package into ``dest``, omitting interpreter caches."""
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(
        REPO_ROOT / "harness" / "src" / "game_sandbox_harness",
        dest,
        ignore=shutil.ignore_patterns("__pycache__", "*.py[cod]"),
    )


def write_base_helpers(dest_sandbox: Path) -> None:
    """Copy shared local-play helpers into the composed template's ``sandbox/`` package."""
    dest_sandbox.mkdir(parents=True, exist_ok=True)
    for name, relative in TEMPLATE_BASE_MODULES.items():
        shutil.copyfile(ENVIRONMENT_PACKAGES_DIR / relative, dest_sandbox / name)
