"""Regenerate everything derived from the canonical schema.

One script, three outputs, run as ``uv run python scripts/generate.py``:

1. Packaged schema copies in the Python harness (``harness/.../schema_data/``).
2. TypeScript type declarations (``schema/ts/src/generated/types.ts``).
3. Golden fixtures written through the real recording store (``schema/fixtures/``).

The packaged copies are written first, with plain file I/O, so the harness is importable
before the fixtures step imports it. CI runs this script and then ``git diff --exit-code``
over the three locations, so any schema edit that was not regenerated fails the build.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys

from _paths import (
    BACKEND_ENVIRONMENTS_JSON,
    BACKEND_GENERATED_DIR,
    ENVIRONMENTS_SRC,
    FIXTURES_DIR,
    HARNESS_SCHEMA_DATA,
    SCHEMA_DIR,
    SCHEMA_FILES,
    TEMPLATE_ENVS,
    TS_GENERATED_DIR,
    TS_GENERATED_TYPES,
    template_sandbox_env,
)

# Pinned so generated output is deterministic across machines and CI.
JSON2TS_VERSION = "15.0.4"

BANNER = (
    "/**\n"
    " * This file is generated by scripts/generate.py from the canonical JSON Schema\n"
    " * under schema/. Do not edit by hand. Run `npm run generate` to regenerate.\n"
    " */\n\n"
)


def copy_packaged_schema() -> None:
    """Copy the canonical schema files byte-for-byte into the harness package data."""
    HARNESS_SCHEMA_DATA.mkdir(parents=True, exist_ok=True)
    for name in SCHEMA_FILES:
        shutil.copyfile(SCHEMA_DIR / name, HARNESS_SCHEMA_DATA / name)
    print(f"  packaged schema -> {HARNESS_SCHEMA_DATA}")


# The top-level sandbox_env/__init__.py of every environment template exposes a uniform
# surface — make_env plus ENV_ID and PLAYER_SLOT — so the env-agnostic base scripts
# (play.py, evaluate.py, tests/) never hardcode an environment. The inner package __init__
# re-exports the factory and is what locally building the env imports. Both are generated;
# a registered env with no entry here fails generation, keeping TEMPLATE_ENVS honest.
_FLAPPY_BIRD_SANDBOX_INIT = '''\
"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/game_sandbox_environments/. Do not
edit by hand. The students' agents run against this vanilla-PettingZoo env locally; only the
steppable environment is synced, never the harness, recording store, or metadata layer.

This template targets Flappy Bird. The base scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from .flappy_bird import NOOP_ACTION, extract_overlay, make_env

ENV_ID = "flappy_bird"
PLAYER_SLOT = "player_0"

__all__ = ["make_env", "extract_overlay", "NOOP_ACTION", "ENV_ID", "PLAYER_SLOT"]
'''

_FLAPPY_BIRD_INNER_INIT = '''\
"""Synced Flappy Bird environment for local development.

GENERATED by scripts/generate.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally not synced; locally you build the env directly:

    from sandbox_env import make_env
"""

from .env import NOOP_ACTION, make_env
from .overlay import extract_overlay

__all__ = ["make_env", "extract_overlay", "NOOP_ACTION"]
'''

# env id -> generated __init__ files, keyed by path relative to that env's sandbox_env/.
_TEMPLATE_ENV_INITS = {
    "flappy_bird": {
        "__init__.py": _FLAPPY_BIRD_SANDBOX_INIT,
        "flappy_bird/__init__.py": _FLAPPY_BIRD_INNER_INIT,
    },
}


def sync_template_env() -> None:
    """Copy the import-self-contained environment modules into each template's sandbox_env/.

    For every environment registered in TEMPLATE_ENVS, only the modules that import nothing
    of ours (relative + third-party imports only) are copied verbatim; the harness-dependent
    package __init__ files are replaced by minimal generated ones (the uniform top-level
    surface plus the inner re-export). The staleness CI job diffs these locations like every
    other generated output, so the template copies are provably current on every PR.
    """
    for env, modules in TEMPLATE_ENVS.items():
        inits = _TEMPLATE_ENV_INITS.get(env)
        if inits is None:
            raise SystemExit(
                f"env {env!r} is registered in TEMPLATE_ENVS but has no generated __init__ "
                f"text in scripts/generate.py; add one before syncing."
            )
        sandbox_env = template_sandbox_env(env)
        if sandbox_env.exists():
            shutil.rmtree(sandbox_env)
        sandbox_env.mkdir(parents=True)

        for relative in modules:
            dest = sandbox_env / relative
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ENVIRONMENTS_SRC / relative, dest)

        for relative, text in inits.items():
            path = sandbox_env / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
        print(f"  template sandbox_env -> {sandbox_env}")


def generate_typescript() -> None:
    """Generate TypeScript declarations from each schema and concatenate into types.ts."""
    TS_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    npx = "npx.cmd" if sys.platform == "win32" else "npx"
    parts: list[str] = [BANNER]
    for name in SCHEMA_FILES:
        result = subprocess.run(
            [
                npx,
                "--yes",
                f"json-schema-to-typescript@{JSON2TS_VERSION}",
                "--input",
                str(SCHEMA_DIR / name),
                "--bannerComment",
                "",
                "--additionalProperties",
                "false",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        parts.append(result.stdout.strip() + "\n")
    TS_GENERATED_TYPES.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"  typescript types -> {TS_GENERATED_TYPES}")


def generate_fixtures() -> None:
    """Write the golden recordings the TypeScript test suite reads back.

    The valid fixtures go through the real FolderRecordingStore (validating on write), so
    they provably come from current Python code. The deliberately-broken bumped-version
    fixture is written raw, since the store would (correctly) refuse to produce it.
    """
    # Import the harness only after the packaged schema exists.
    from game_sandbox_harness.recording.local import FolderRecordingStore
    from game_sandbox_harness.state import build_agent_step, build_header, build_step_state

    if FIXTURES_DIR.exists():
        shutil.rmtree(FIXTURES_DIR)
    store = FolderRecordingStore(FIXTURES_DIR)

    def step(tick: int):
        return build_step_state(
            tick=tick,
            agents={
                "player_0": build_agent_step(
                    reward=float(tick),
                    score=float(tick),
                    observation={"y": tick},
                    action=tick % 2,
                    decision_ms=0.5,
                )
            },
            started_at=1_700_000_000_000 + tick,
            duration_ms=1.0,
            overlay={"pipes": [{"x": 100 - tick, "gap_y": 50}]},
        )

    # 1. A two-step recording that must parse into generated types with no casts.
    with store.create("two-step", build_header(environment="flappy", seed=7)) as writer:
        writer.write_step(step(0))
        writer.write_step(step(1))

    # 2. A recording whose header declares an unknown sidecar that must load cleanly.
    with store.create(
        "unknown-sidecar",
        build_header(
            environment="flappy",
            seed=7,
            sidecars=[{"name": "future-telemetry", "path": "telemetry.jsonl"}],
        ),
    ) as writer:
        writer.write_step(step(0))

    # 3. A bumped-version recording that must be rejected by a version-1 reader. Written
    #    raw because the store validates on write and would refuse schema_version 2.
    bumped_dir = FIXTURES_DIR / "bumped-version"
    bumped_dir.mkdir(parents=True, exist_ok=True)
    bumped_header = {"schema_version": 2, "environment": "flappy"}
    bumped_state = {
        "schema_version": 2,
        "tick": 0,
        "agents": {"player_0": {"reward": 0.0, "score": 0.0}},
        "timing": {"started_at": 1_700_000_000_000, "duration_ms": 1.0},
    }
    (bumped_dir / "recording.jsonl").write_text(
        json.dumps(bumped_header, separators=(",", ":"), sort_keys=True)
        + "\n"
        + json.dumps(bumped_state, separators=(",", ":"), sort_keys=True)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"  fixtures -> {FIXTURES_DIR}")


def generate_environments_json() -> None:
    """Write the backend's environment metadata artifact from the Python registry.

    The backend never runs Python, so it reads this committed JSON file instead of importing
    the registry. Each entry is its ``EnvironmentMeta.to_json()`` (which already carries
    ``env_id``); the array is sorted by id and the keys are sorted so the bytes are stable
    across machines, like every other generated artifact. The generated-code-fresh CI job
    diffs this path, so it cannot drift from ``discover_environments()``.
    """
    # Imported here so the harness/environments are only required when this step runs.
    from game_sandbox_harness.environment import discover_environments

    entries = discover_environments()
    metas = [entries[env_id].meta.to_json() for env_id in sorted(entries)]

    BACKEND_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    BACKEND_ENVIRONMENTS_JSON.write_text(
        json.dumps(metas, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"  environments metadata -> {BACKEND_ENVIRONMENTS_JSON}")


def main() -> int:
    print("Regenerating schema-derived artifacts:")
    copy_packaged_schema()
    sync_template_env()
    generate_typescript()
    generate_fixtures()
    generate_environments_json()
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
