"""Regenerate everything derived from the canonical schema.

One script refreshes every generated artifact, run as ``uv run python scripts/generate.py``:

1. Packaged schema copies in the Python harness (``harness/.../schema_data/``).
2. TypeScript type declarations (``schema/ts/src/generated/types.ts``).
3. Golden fixtures written through the real recording store (``schema/fixtures/``).
4. Environment copies and the relocated harness in student templates.

The packaged copies are written first, with plain file I/O, so the harness is importable
before the fixtures step imports it. CI runs this script and then ``git diff --exit-code``
over the three locations, so any schema edit that was not regenerated fails the build.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

from _envs import discover_environments, package_dirs
from _paths import (
    BACKEND_ENVIRONMENTS_JSON,
    BACKEND_GENERATED_DIR,
    ENVIRONMENTS_PYPROJECT,
    ENVIRONMENTS_SRC,
    FIXTURES_DIR,
    HARNESS_SCHEMA_DATA,
    REPO_ROOT,
    RETIRED_TEMPLATE_BASE_PATHS,
    SCHEMA_DIR,
    SCHEMA_FILES,
    TEMPLATE_BASE_MODULES,
    TEMPLATES_DIR,
    TS_GENERATED_DIR,
    TS_GENERATED_TYPES,
    TemplateEnvironmentSpec,
    template_sandbox_base,
    template_sandbox_env,
    template_sandbox_harness,
)

# Pinned so generated output is deterministic across machines and CI.
JSON2TS_VERSION = "15.0.4"

BANNER = (
    "/**\n"
    " * This file is generated by scripts/generate.py from the canonical JSON Schema\n"
    " * under schema/. Do not edit by hand. Run `npm run generate` to regenerate.\n"
    " */\n\n"
)

_TEMPLATE_ENV_SENTINEL = "# GAME-SANDBOX-GENERATED-ENV: scripts/generate.py"


def copy_packaged_schema() -> None:
    """Copy the canonical schema files byte-for-byte into the harness package data."""
    HARNESS_SCHEMA_DATA.mkdir(parents=True, exist_ok=True)
    for name in SCHEMA_FILES:
        shutil.copyfile(SCHEMA_DIR / name, HARNESS_SCHEMA_DATA / name)
    print(f"  packaged schema -> {HARNESS_SCHEMA_DATA}")


# The top-level sandbox/env/__init__.py of every environment template exposes a uniform
# surface: make_env, hooks, public metadata, and the selected player slot. The env-agnostic
# provided scripts (sandbox/play.py, sandbox/evaluate.py, tests/) never hardcode an environment.
# The inner package __init__ re-exports the factory and is what locally building the env imports.
# Everything in those two files is boilerplate shared across template layers except a handful of
# Per-environment facts and copied modules come from the same discovered package, so generation
# cannot render an init whose package facts disagree with its synchronized source list.
def _render_metadata_mapping(metadata: dict[str, object]) -> str:
    """Render registry metadata in the same shape Ruff would format it."""
    lines = ["    **{"]
    for key, value in metadata.items():
        prefix = f'        "{key}": '
        if isinstance(value, str) and len(prefix) + len(json.dumps(value)) > 110:
            chunks = textwrap.wrap(value, width=88, break_long_words=False, break_on_hyphens=False)
            lines.append(f"{prefix}(")
            for index, chunk in enumerate(chunks):
                suffix = " " if index < len(chunks) - 1 else ""
                lines.append(f"            {json.dumps(chunk + suffix)}")
            lines.append("        ),")
        elif isinstance(value, str):
            lines.append(f"{prefix}{json.dumps(value)},")
        elif isinstance(value, tuple):
            items = ", ".join(json.dumps(item) for item in value)
            trailing_comma = "," if len(value) == 1 else ""
            lines.append(f"{prefix}({items}{trailing_comma}),")
        else:
            lines.append(f"{prefix}{value!r},")
    lines.append("    }")
    return "\n".join(lines)


def _render_sandbox_init(env_id: str, spec: TemplateEnvironmentSpec, meta: object) -> str:
    """Render the top-level ``sandbox/env/__init__.py`` (the uniform, env-agnostic surface)."""
    from game_sandbox_harness.environment import EnvironmentMeta

    if not isinstance(meta, EnvironmentMeta):
        raise TypeError(f"expected EnvironmentMeta for {env_id!r}, got {type(meta).__name__}")
    metadata = meta.to_json()
    metadata["human_slots"] = tuple(metadata["human_slots"])
    metadata_text = _render_metadata_mapping(metadata)
    surface_import = f"from .{spec.inner_package} import {spec.default_action}, extract_overlay, make_env"
    return f'''\
{_TEMPLATE_ENV_SENTINEL}
"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/. Do not edit by hand. The students'
agents run against this vanilla-PettingZoo environment locally. ``META`` is the complete public
registry metadata used by the browser relay and the injected harness entry.

This template targets {spec.display_name}. The provided scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from sandbox.harness.environment import EnvironmentMeta

{surface_import}

ENV_ID = "{env_id}"
PLAYER_SLOT = "{spec.player_slot}"
META = EnvironmentMeta(
{metadata_text}
)

__all__ = [
    "make_env",
    "extract_overlay",
    "{spec.default_action}",
    "ENV_ID",
    "PLAYER_SLOT",
    "META",
]
'''


def _render_inner_init(spec: TemplateEnvironmentSpec) -> str:
    """Render the inner ``sandbox/env/<pkg>/__init__.py`` (re-exports the synced factory)."""
    return f'''\
"""Synced {spec.display_name} environment for local development.

GENERATED by scripts/generate.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally not synced; locally you build the env directly:

    from sandbox.env import make_env
"""

from .env import {spec.default_action}, make_env
from .overlay import extract_overlay

__all__ = ["make_env", "extract_overlay", "{spec.default_action}"]
'''


def sync_environments_pyproject() -> None:
    """Regenerate environment entry points and wheel-package lists between owned markers."""
    discovered = discover_environments()
    entry_points = "\n".join(f'{env_id} = "{env_id}:ENTRY"' for env_id in discovered)
    packages = ", ".join(f'"src/{path.name}"' for path in package_dirs())
    replacements = {
        "# BEGIN GENERATED ENTRY POINTS": entry_points,
        "# BEGIN GENERATED WHEEL PACKAGES": f"packages = [{packages}]",
    }
    text = ENVIRONMENTS_PYPROJECT.read_text(encoding="utf-8")
    for begin, body in replacements.items():
        end = begin.replace("BEGIN", "END")
        start_index = text.find(begin)
        end_index = text.find(end)
        if start_index < 0 or end_index < 0 or end_index < start_index:
            raise RuntimeError(f"missing or malformed generated block {begin!r} in {ENVIRONMENTS_PYPROJECT}")
        content_start = start_index + len(begin)
        text = text[:content_start] + f"\n{body}\n" + text[end_index:]
    ENVIRONMENTS_PYPROJECT.write_text(text, encoding="utf-8", newline="\n")
    print(f"  environment packaging -> {ENVIRONMENTS_PYPROJECT}")


def is_generated_template_env(path: Path) -> bool:
    """Return whether a template environment directory carries the exact ownership sentinel."""
    init = path / "__init__.py"
    return init.is_file() and init.read_text(encoding="utf-8").startswith(f"{_TEMPLATE_ENV_SENTINEL}\n")


def sync_template_env() -> None:
    """Copy the import-self-contained environment modules into each template's sandbox/env/.

    For every recognized environment, only the modules that import nothing
    of ours (relative + third-party imports only) are copied verbatim; the harness-dependent
    package __init__ files are replaced by minimal generated ones (the uniform top-level
    surface plus the inner re-export). The staleness CI job diffs these locations like every
    other generated output, so the template copies are provably current on every PR.
    """
    discovered_environments = discover_environments()
    if TEMPLATES_DIR.is_dir():
        for layer in TEMPLATES_DIR.iterdir():
            generated_env = layer / "sandbox" / "env"
            if (
                layer.is_dir()
                and layer.name not in discovered_environments
                and is_generated_template_env(generated_env)
            ):
                shutil.rmtree(generated_env)
                print(f"  retired template sandbox/env -> {generated_env}")

    for env, discovered in discovered_environments.items():
        spec = discovered.spec
        sandbox_env = template_sandbox_env(env)
        if sandbox_env.exists():
            if not is_generated_template_env(sandbox_env):
                raise RuntimeError(f"refusing to replace unowned template environment at {sandbox_env}")
            shutil.rmtree(sandbox_env)
        sandbox_env.mkdir(parents=True)

        for relative in spec.modules:
            dest = sandbox_env / relative
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ENVIRONMENTS_SRC / relative, dest)

        inits = {
            "__init__.py": _render_sandbox_init(env, spec, discovered.entry.meta),
            f"{spec.inner_package}/__init__.py": _render_inner_init(spec),
        }
        for relative, text in inits.items():
            path = sandbox_env / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
        print(f"  template sandbox/env -> {sandbox_env}")


def sync_template_base() -> None:
    """Reconcile the few remaining generated base helpers without touching hand-authored modules."""
    sandbox = template_sandbox_base()
    for relative in RETIRED_TEMPLATE_BASE_PATHS:
        path = sandbox / relative
        if path.exists():
            path.unlink()
            print(f"  retired template sandbox path -> {path}")
    for name, relative in TEMPLATE_BASE_MODULES.items():
        shutil.copyfile(ENVIRONMENTS_SRC / relative, sandbox / name)
        print(f"  template sandbox -> {sandbox / name}")


def _replace_owned_directory(source: Path, destination: Path, label: str) -> None:
    """Replace one generated directory without copying interpreter cache artifacts."""
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns("__pycache__", "*.py[cod]"))
    print(f"  {label} -> {destination}")


def sync_template_harness() -> None:
    """Copy the relocatable harness package, including generated schema data, into the template."""
    _replace_owned_directory(
        REPO_ROOT / "harness" / "src" / "game_sandbox_harness",
        template_sandbox_harness(),
        "template sandbox/harness",
    )


def generate_typescript() -> None:
    """Generate TypeScript declarations from each schema and concatenate into types.ts."""
    TS_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    npx = "npx.cmd" if sys.platform == "win32" else "npx"
    parts: list[str] = [BANNER]
    for name in SCHEMA_FILES:
        result = subprocess.run(
            [
                npx,
                "--yes",
                f"json-schema-to-typescript@{JSON2TS_VERSION}",
                "--input",
                str(SCHEMA_DIR / name),
                "--bannerComment",
                "",
                "--additionalProperties",
                "false",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        parts.append(result.stdout.strip() + "\n")
    TS_GENERATED_TYPES.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"  typescript types -> {TS_GENERATED_TYPES}")


def generate_fixtures() -> None:
    """Write the golden recordings the TypeScript test suite reads back.

    The valid fixtures go through the real FolderRecordingStore (validating on write), so
    they provably come from current Python code. The deliberately-broken bumped-version
    fixture is written raw, since the store would (correctly) refuse to produce it.
    """
    # Import the harness only after the packaged schema exists.
    from game_sandbox_harness.recording.local import FolderRecordingStore
    from game_sandbox_harness.state import build_agent_step, build_header, build_step_state

    if FIXTURES_DIR.exists():
        shutil.rmtree(FIXTURES_DIR)
    store = FolderRecordingStore(FIXTURES_DIR)

    def step(tick: int):
        return build_step_state(
            tick=tick,
            agents={
                "player_0": build_agent_step(
                    reward=float(tick),
                    score=float(tick),
                    observation={"y": tick},
                    action=tick % 2,
                    decision_ms=0.5,
                )
            },
            started_at=1_700_000_000_000 + tick,
            duration_ms=1.0,
            overlay={"pipes": [{"x": 100 - tick, "gap_y": 50}]},
        )

    # 1. A two-step recording that must parse into generated types with no casts. It carries a
    #    per-slot players block so the generated `players` field is exercised by the read-back test.
    with store.create(
        "two-step",
        build_header(
            environment="flappy",
            seed=7,
            players={"player_0": {"kind": "agent", "label": "Naive agent"}},
        ),
    ) as writer:
        writer.write_step(step(0))
        writer.write_step(step(1))

    # 2. A chatty recording whose step carries a `messages` array (one targeted, one broadcast) and
    #    a `chat_ms` timing field, so the TypeScript read-back test pins that the regenerated types
    #    carry both without a cast. Two slots so the targeted message names a real recipient.
    with store.create(
        "chatty",
        build_header(
            environment="spades",
            seed=7,
            players={
                "player_0": {"kind": "agent", "label": "Signaler"},
                "player_1": {"kind": "agent", "label": "Naive agent"},
            },
        ),
    ) as writer:
        writer.write_step(
            build_step_state(
                tick=0,
                agents={
                    "player_0": build_agent_step(
                        reward=0.0,
                        score=0.0,
                        action=57,
                        decision_ms=0.5,
                        chat_ms=0.25,
                    )
                },
                started_at=1_700_000_000_000,
                duration_ms=1.0,
                messages=[
                    {"from": "player_0", "to": "player_1", "text": "strong:hearts"},
                    {"from": "player_0", "to": None, "text": "good luck"},
                ],
            )
        )

    # 3. A recording whose header declares an unknown sidecar that must load cleanly.
    with store.create(
        "unknown-sidecar",
        build_header(
            environment="flappy",
            seed=7,
            sidecars=[{"name": "future-telemetry", "path": "telemetry.jsonl"}],
        ),
    ) as writer:
        writer.write_step(step(0))

    # 4. A bumped-version recording that must be rejected by a version-1 reader. Written
    #    raw because the store validates on write and would refuse schema_version 2.
    bumped_dir = FIXTURES_DIR / "bumped-version"
    bumped_dir.mkdir(parents=True, exist_ok=True)
    bumped_header = {"schema_version": 2, "environment": "flappy"}
    bumped_state = {
        "schema_version": 2,
        "tick": 0,
        "agents": {"player_0": {"reward": 0.0, "score": 0.0}},
        "timing": {"started_at": 1_700_000_000_000, "duration_ms": 1.0},
    }
    (bumped_dir / "recording.jsonl").write_text(
        json.dumps(bumped_header, separators=(",", ":"), sort_keys=True)
        + "\n"
        + json.dumps(bumped_state, separators=(",", ":"), sort_keys=True)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"  fixtures -> {FIXTURES_DIR}")


def generate_environments_json() -> None:
    """Write the backend's environment metadata artifact from discovered source packages.

    The backend never runs Python, so it reads this committed JSON file instead of importing
    the registry. Each entry is its ``EnvironmentMeta.to_json()`` (which already carries
    ``env_id``); the array is sorted by id and the keys are sorted so the bytes are stable
    across machines, like every other generated artifact. The generated-code-fresh CI job
    diffs this path, so it cannot drift from source discovery.
    """
    entries = discover_environments()
    metas = [entries[env_id].entry.meta.to_json() for env_id in sorted(entries)]

    BACKEND_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    BACKEND_ENVIRONMENTS_JSON.write_text(
        json.dumps(metas, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"  environments metadata -> {BACKEND_ENVIRONMENTS_JSON}")


def main() -> int:
    print("Regenerating schema-derived artifacts:")
    copy_packaged_schema()
    sync_environments_pyproject()
    sync_template_env()
    sync_template_base()
    sync_template_harness()
    generate_typescript()
    generate_fixtures()
    generate_environments_json()
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
