"""Interactively configure and start a Game Sandbox checkout."""

from __future__ import annotations

import argparse
import secrets
import shutil
import subprocess
import sys
from collections.abc import Callable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse

from _paths import REPO_ROOT
from ci import _NPM, _wait_for_http

DEV_AUTH_SECRET = "dev-secret-do-not-deploy-32-chars"
DEV_ADMIN_EMAIL = "admin@example.com"
DEV_ADMIN_PASSWORD = "admin-dev-password"
DEFAULT_PORT = "8080"
NODE_MAJOR = 22


def _assignments(text: str) -> Iterator[tuple[str, str]]:
    """Yield ``(key, raw value)`` for every assignment line, skipping blanks and comments."""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, raw_value = stripped.split("=", 1)
        if key.strip():
            yield key.strip(), raw_value.strip()


def _unquote_env_value(raw: str) -> str:
    if len(raw) >= 2 and raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1]
    return raw


def _quote_env_value(value: str) -> str:
    return f'"{value}"' if any(character in value for character in " #") else value


def parse_env_file(text: str) -> dict[str, str]:
    """Parse the ``KEY=value`` form used by the project's env files."""
    return {key: _unquote_env_value(raw) for key, raw in _assignments(text)}


def render_env_file(pairs: Mapping[str, str], preserved: Sequence[str] = ()) -> str:
    """Render the managed values, then the assignment lines setup does not manage."""
    lines = [
        "# Generated by scripts/setup.py. Existing comments are kept in .env.bak.",
        "# Private deployment values belong in this file, not in version control.",
        "",
        *(f"{key}={_quote_env_value(pairs[key])}" for key in MANAGED_KEYS if key in pairs),
        *preserved,
    ]
    return "\n".join(lines) + "\n"


def validate_env_value(value: str) -> str | None:
    """Reject the characters whose meaning differs between the readers of an env file.

    The backend reads ``.env`` with Node's ``util.parseEnv`` and Docker Compose reads it as an
    ``env_file``. The two disagree about backslash and quote escapes inside a value, so setup writes
    only the subset they read alike: a value may be wrapped in double quotes but never escape one.
    """
    if '"' in value or "\\" in value:
        return "Enter a value without double quotes or backslashes."
    return None


def _url_error(value: str, requirement: str, *, allow_path: bool) -> str | None:
    try:
        parsed = urlparse(value)
        _ = parsed.port
    except ValueError:
        return requirement
    if (
        value != value.strip()
        or any(character.isspace() for character in value)
        or parsed.scheme not in {"http", "https"}
        or not parsed.netloc
        or parsed.username is not None
        or parsed.password is not None
        or (not allow_path and parsed.path not in {"", "/"})
        or parsed.params
        or parsed.query
        or parsed.fragment
    ):
        return requirement
    return None


def validate_origin(value: str, _mode: str = "") -> str | None:
    requirement = "Enter a bare absolute http(s) origin with no path, query, or fragment."
    return _url_error(value, requirement, allow_path=False)


def validate_http_url(value: str, _mode: str = "") -> str | None:
    requirement = "Enter an absolute http(s) URL without credentials, a query, or a fragment."
    return _url_error(value, requirement, allow_path=True)


def validate_auth_secret(value: str) -> str | None:
    if len(value) < 32 or value == DEV_AUTH_SECRET:
        return "AUTH_SECRET must be at least 32 characters and must not use the development secret."
    return None


def validate_admin_email(value: str, _mode: str = "") -> str | None:
    if (
        value.lower() == DEV_ADMIN_EMAIL
        or "@" not in value
        or any(character.isspace() for character in value)
    ):
        return "Enter a real administrator email address."
    return None


def validate_admin_password(value: str, _mode: str = "") -> str | None:
    if not value or value == DEV_ADMIN_PASSWORD:
        return "Choose an administrator password other than the development password."
    return None


def validate_data_dir(value: str, mode: str) -> str | None:
    if not value:
        return "The data directory is required."
    if mode == "docker" and not value.startswith("/"):
        return "Docker deployment needs an absolute data directory shared by the host and container."
    return None


def validate_oauth(client_id: str, client_secret: str) -> str | None:
    if bool(client_id) != bool(client_secret):
        return "GitHub OAuth needs both a client ID and a client secret."
    return None


def validate_port(value: str, _mode: str = "") -> str | None:
    if not value.isdigit() or not 1 <= int(value) <= 65535:
        return "The site port must be an integer from 1 through 65535."
    return None


def docker_mode_error(platform: str) -> str | None:
    if platform in {"win32", "darwin"}:
        return (
            "Docker deployment needs a Linux Docker daemon because the data directory must have the same "
            "path on the host and in the app container. Use host mode, or run under WSL2."
        )
    return None


PromptDefault = Callable[[str], str]
PromptValidator = Callable[[str, str], str | None]


def _empty_default(_mode: str) -> str:
    return ""


def _fixed_default(value: str) -> PromptDefault:
    return lambda _mode: value


def _password_default(_mode: str) -> str:
    return secrets.token_urlsafe(12)


def _data_dir_default(mode: str) -> str:
    return "/srv/game-sandbox/data" if mode == "docker" else "backend/data"


@dataclass(frozen=True)
class EnvField:
    """Metadata for one setup-managed environment value."""

    label: str
    help_text: str = ""
    required: bool = False
    prompt_group: str | None = None
    allow_blank: bool = False
    default: PromptDefault = _empty_default
    validator: PromptValidator | None = None


ENV_FIELDS = {
    "PUBLIC_ORIGIN": EnvField(
        "Public site URL",
        "The web address participants will use to open Game Sandbox.",
        required=True,
        prompt_group="site",
        validator=validate_origin,
    ),
    "PORT": EnvField(
        "Site port",
        required=True,
        prompt_group="site",
        default=_fixed_default(DEFAULT_PORT),
        validator=validate_port,
    ),
    "AUTH_SECRET": EnvField("Authentication secret", required=True),
    "ADMIN_EMAIL": EnvField(
        "Administrator email address",
        required=True,
        prompt_group="administrator",
        validator=validate_admin_email,
    ),
    "ADMIN_PASSWORD": EnvField(
        "Administrator password",
        required=True,
        prompt_group="administrator",
        default=_password_default,
        validator=validate_admin_password,
    ),
    "ADMIN_NAME": EnvField(
        "Administrator name",
        required=True,
        prompt_group="administrator",
        default=_fixed_default("Admin"),
    ),
    "AUTH_ALLOW_INSECURE_DEFAULTS": EnvField("Allow insecure development defaults", required=True),
    "DATA_DIR": EnvField(
        "Data directory",
        "Game data, recordings, and the database will be stored here.",
        required=True,
        prompt_group="storage",
        default=_data_dir_default,
        validator=validate_data_dir,
    ),
    "GITHUB_OAUTH_CLIENT_ID": EnvField("GitHub OAuth client ID", prompt_group="oauth"),
    "GITHUB_OAUTH_CLIENT_SECRET": EnvField("GitHub OAuth client secret", prompt_group="oauth"),
    "GITHUB_TOKEN": EnvField(
        "GitHub repository access token",
        "Optional. This allows submissions from private GitHub repositories.",
        prompt_group="github",
        allow_blank=True,
    ),
    "LLM_UPSTREAM_URL": EnvField(
        "AI provider URL",
        "The base URL of your OpenAI-compatible provider.",
        prompt_group="ai",
        validator=validate_http_url,
    ),
    "LLM_UPSTREAM_KEY": EnvField("AI provider API key", prompt_group="ai", allow_blank=True),
    "LLM_MODEL_LARGE": EnvField("Large model name", prompt_group="ai", allow_blank=True),
    "LLM_MODEL_MEDIUM": EnvField("Medium model name", prompt_group="ai", allow_blank=True),
    "LLM_MODEL_SMALL": EnvField("Small model name", prompt_group="ai", allow_blank=True),
}
MANAGED_KEYS = tuple(ENV_FIELDS)
MANAGED_KEY_SET = frozenset(MANAGED_KEYS)
REQUIRED_ENV_KEYS = frozenset(key for key, field in ENV_FIELDS.items() if field.required)


@dataclass(frozen=True)
class WizardChoice:
    title: str
    description: str


MODES = {
    "dev": WizardChoice("Local development", "For contributing or trying Game Sandbox locally."),
    "host": WizardChoice(
        "Run on this computer",
        "For a long-running site without putting the app itself in Docker.",
    ),
    "docker": WizardChoice(
        "Docker on a Linux server",
        "For a self-contained deployment on Linux or inside WSL2.",
    ),
}

PROMPT_GROUPS = {
    "site": WizardChoice("Site", "Choose where people will open Game Sandbox."),
    "administrator": WizardChoice("Administrator account", "Create the account that manages the site."),
    "storage": WizardChoice("Storage", "Choose where Game Sandbox will keep its data."),
    "oauth": WizardChoice("GitHub sign-in", "Allow participants to sign in with their GitHub accounts."),
    "github": WizardChoice(
        "Private GitHub repositories",
        "Add a token only if submissions may come from private repositories.",
    ),
    "ai": WizardChoice("AI provider", "Connect an OpenAI-compatible provider for agent access."),
}


def plan_env(mode: str, answers: Mapping[str, str], existing: Mapping[str, str]) -> dict[str, str]:
    """Return the managed deployment values without reading files or prompting."""
    if mode not in {"host", "docker"}:
        raise ValueError("Only host and docker modes write a deployment environment.")

    values = {key: answers.get(key, "").strip() for key in MANAGED_KEYS}
    values["AUTH_SECRET"] = existing.get("AUTH_SECRET", "")
    if validate_auth_secret(values["AUTH_SECRET"]):
        values["AUTH_SECRET"] = secrets.token_hex(32)
    values["AUTH_ALLOW_INSECURE_DEFAULTS"] = "false"

    errors = (
        validate_origin(values["PUBLIC_ORIGIN"]),
        validate_admin_email(values["ADMIN_EMAIL"]),
        validate_admin_password(values["ADMIN_PASSWORD"]),
        None if values["ADMIN_NAME"] else "The administrator name is required.",
        validate_data_dir(values["DATA_DIR"], mode),
        validate_port(values["PORT"]),
        validate_oauth(values["GITHUB_OAUTH_CLIENT_ID"], values["GITHUB_OAUTH_CLIENT_SECRET"]),
    )
    if error := next((message for message in errors if message), None):
        raise ValueError(error)

    llm_values = (values["LLM_MODEL_LARGE"], values["LLM_MODEL_MEDIUM"], values["LLM_MODEL_SMALL"])
    if values["LLM_UPSTREAM_URL"]:
        if validate_http_url(values["LLM_UPSTREAM_URL"]):
            raise ValueError("The LLM provider URL must be an absolute http(s) URL.")
        if not any(llm_values):
            raise ValueError("Enable the LLM proxy with at least one model name.")
    elif any(llm_values) or values["LLM_UPSTREAM_KEY"]:
        raise ValueError("The LLM provider URL is required when configuring the LLM proxy.")
    return {key: value for key, value in values.items() if key in REQUIRED_ENV_KEYS or value}


def write_env_file(path: Path, pairs: Mapping[str, str], previous_text: str) -> None:
    """Back up any existing env file, then write the managed values above the untouched lines.

    Lines setting keys setup does not manage are copied across exactly as they were written, so a
    hand-edited value keeps whatever quoting its author chose.
    """
    if path.exists():
        shutil.copy2(path, path.with_name(f"{path.name}.bak"))
    preserved = [f"{key}={raw}" for key, raw in _assignments(previous_text) if key not in MANAGED_KEY_SET]
    path.write_text(render_env_file(pairs, preserved), encoding="utf-8")


def prompt(
    label: str,
    default: str = "",
    validator: Callable[[str], str | None] | None = None,
    *,
    allow_blank: bool = False,
) -> str:
    """Ask for one value, retrying until it is usable. An empty line takes the shown default."""
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip() or default
        if not value:
            if allow_blank:
                return ""
            print("This value is required.")
            continue
        error = validate_env_value(value) or (validator(value) if validator else None)
        if error:
            print(error)
            continue
        return value


def prompt_yes_no(label: str, default: bool = False) -> bool:
    suffix = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{suffix}]: ").strip().lower()
        if not value:
            return default
        if value in {"y", "yes"}:
            return True
        if value in {"n", "no"}:
            return False
        print("Enter y or n.")


def _prompt_field(key: str, mode: str, existing: Mapping[str, str]) -> str:
    field = ENV_FIELDS[key]
    if field.help_text:
        print(field.help_text)
    default = existing.get(key) or field.default(mode)
    validator = field.validator
    bound = None if validator is None else (lambda value: validator(value, mode))
    return prompt(field.label, default, bound, allow_blank=field.allow_blank)


def _collect_group(group: str, mode: str, existing: Mapping[str, str]) -> dict[str, str]:
    return {
        key: _prompt_field(key, mode, existing)
        for key, field in ENV_FIELDS.items()
        if field.prompt_group == group
    }


def _print_group(group: str) -> None:
    metadata = PROMPT_GROUPS[group]
    print(f"\n{metadata.title}")
    print(metadata.description)


def collect_answers(mode: str, existing: Mapping[str, str]) -> dict[str, str]:
    """Collect the shared host and Docker deployment settings."""
    print("\nDeployment settings")
    print("Press Enter to keep a suggested value shown in brackets.")
    answers: dict[str, str] = {}
    for group in ("site", "administrator", "storage"):
        _print_group(group)
        answers.update(_collect_group(group, mode, existing))

    _print_group("oauth")
    has_oauth = bool(existing.get("GITHUB_OAUTH_CLIENT_ID") and existing.get("GITHUB_OAUTH_CLIENT_SECRET"))
    if prompt_yes_no("Set up GitHub sign-in", has_oauth):
        answers.update(_collect_group("oauth", mode, existing))
    else:
        answers["GITHUB_OAUTH_CLIENT_ID"] = ""
        answers["GITHUB_OAUTH_CLIENT_SECRET"] = ""

    _print_group("github")
    answers.update(_collect_group("github", mode, existing))

    _print_group("ai")
    has_llm = bool(existing.get("LLM_UPSTREAM_URL"))
    if prompt_yes_no("Connect an AI provider", has_llm):
        answers.update(_collect_group("ai", mode, existing))
        model_keys = ("LLM_MODEL_LARGE", "LLM_MODEL_MEDIUM", "LLM_MODEL_SMALL")
        while not any(answers[key] for key in model_keys):
            print("Choose at least one model before continuing.")
            for key in model_keys:
                answers[key] = _prompt_field(key, mode, {})
    else:
        answers.update(
            {
                "LLM_UPSTREAM_URL": "",
                "LLM_UPSTREAM_KEY": "",
                "LLM_MODEL_LARGE": "",
                "LLM_MODEL_MEDIUM": "",
                "LLM_MODEL_SMALL": "",
            }
        )
    return answers


def _print_technical_details(*outputs: str) -> None:
    details = [output.rstrip() for output in outputs if output and output.strip()]
    if details:
        print("\nTechnical details:")
        print("\n".join(details))


def _run_step(label: str, command: list[str], *, success: str = "done") -> None:
    """Run one installer step with concise output and useful failure details."""
    print(f"{label}...", end=" ", flush=True)
    try:
        result = subprocess.run(
            command,
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as error:
        print("failed.")
        print(f"We could not complete this step: {label.strip()}.")
        _print_technical_details(str(error))
        raise SystemExit(1) from None
    if result.returncode != 0:
        print("failed.")
        print(f"We could not complete this step: {label.strip()}.")
        _print_technical_details(result.stdout, result.stderr)
        raise SystemExit(result.returncode)
    print(f"{success}.")


def _start_foreground() -> int:
    command = [_NPM, "start"]
    print("\nStarting Game Sandbox. Press Ctrl+C to stop.", flush=True)
    try:
        process = subprocess.Popen(command, cwd=REPO_ROOT)
    except OSError as error:
        print("Game Sandbox could not start.")
        _print_technical_details(str(error))
        raise SystemExit(1) from None
    try:
        return process.wait()
    except KeyboardInterrupt:
        return process.wait()


def _print_deploy_summary(mode: str, values: Mapping[str, str]) -> None:
    print("\nSetup complete")
    print("Game Sandbox is running." if mode == "docker" else "Game Sandbox is ready to start.")
    print(f"Open it at: {values['PUBLIC_ORIGIN']}")

    print("\nAdministrator sign-in")
    print(f"  Email: {values['ADMIN_EMAIL']}")
    print(f"  Password: {values['ADMIN_PASSWORD']}")
    print(f"\nData will be stored in: {values['DATA_DIR']}")
    if values.get("GITHUB_OAUTH_CLIENT_ID"):
        origin = values["PUBLIC_ORIGIN"].rstrip("/")
        print("\nOne last step for GitHub sign-in")
        print("Add this callback URL to your GitHub app:")
        print(f"  {origin}/api/auth/callback/github")

    print("\nHelpful commands")
    if mode == "docker":
        print("  View logs: docker compose logs -f app")
        print("  Stop Game Sandbox: docker compose down")
    else:
        print("  Start Game Sandbox: npm start")
    print("\nThe first game session builds its base image, which can take a while.")


def run_dev() -> int:
    """Install local development dependencies and optionally start the app."""
    env_path = REPO_ROOT / ".env"
    has_custom_settings = env_path.exists()
    if has_custom_settings:
        print("Note: your existing .env file overrides the local development defaults.")
    print("\nPreparing local development")
    _run_step("Installing Python dependencies", ["uv", "sync"])
    _run_step("Installing web dependencies", [_NPM, "install"])
    print("\nSetup complete. Local development is ready.")
    if has_custom_settings:
        print("Your existing .env settings will be used when Game Sandbox starts.")
    else:
        print(f"  Site: http://localhost:{DEFAULT_PORT}")
        print(f"  Administrator email: {DEV_ADMIN_EMAIL}")
        print(f"  Administrator password: {DEV_ADMIN_PASSWORD}")
    print("\nFor a database with sample data, run: npm run demo")
    if prompt_yes_no("Start the app now", True):
        return _start_foreground()
    print("You can start it later with: npm start")
    return 0


def _configure_deployment(mode: str) -> dict[str, str]:
    """Collect the deployment settings, write ``.env``, and create the data directory."""
    env_path = REPO_ROOT / ".env"
    try:
        previous_text = env_path.read_text(encoding="utf-8") if env_path.exists() else ""
    except OSError as error:
        print("\nWe could not read your existing settings.")
        _print_technical_details(str(error))
        raise SystemExit(1) from None
    existing = parse_env_file(previous_text)
    values = plan_env(mode, collect_answers(mode, existing), existing)
    print("\nSaving your settings...", end=" ", flush=True)
    try:
        write_env_file(env_path, values, previous_text)
        data_dir = Path(values["DATA_DIR"])
        (data_dir if data_dir.is_absolute() else REPO_ROOT / data_dir).mkdir(parents=True, exist_ok=True)
    except OSError as error:
        print("failed.")
        print("We could not save your settings.")
        _print_technical_details(str(error))
        raise SystemExit(1) from None
    print("done.")
    if previous_text:
        print("Your previous settings were saved as .env.bak.")
    return values


def run_host() -> int:
    """Configure a host-process deployment and optionally run it in the foreground."""
    values = _configure_deployment("host")
    print("\nPreparing the host deployment")
    _run_step("Installing web dependencies", [_NPM, "install"])
    _print_deploy_summary("host", values)
    if prompt_yes_no("Start the app now", True):
        return _start_foreground()
    print("You can start it later with: npm start")
    return 0


def run_docker() -> int:
    """Configure and launch a Linux containerized deployment."""
    values = _configure_deployment("docker")
    print("\nPreparing the Docker deployment")
    print("The initial build may take several minutes.")
    _run_step(
        "Building and starting Game Sandbox",
        ["docker", "compose", "up", "-d", "--build"],
    )
    print("Waiting for Game Sandbox to become ready...", end=" ", flush=True)
    try:
        _wait_for_http(f"http://127.0.0.1:{values['PORT']}/api/environments", 300)
        print("done.")
    except (SystemExit, Exception) as error:
        print("failed.")
        print("Game Sandbox started, but it did not become ready in time.")
        try:
            logs = subprocess.run(
                ["docker", "compose", "logs", "--tail", "100", "app"],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            _print_technical_details(str(error), logs.stdout, logs.stderr)
        except OSError as logs_error:
            _print_technical_details(str(error), str(logs_error))
        raise SystemExit(1) from None
    _print_deploy_summary("docker", values)
    return 0


def choose_mode() -> str:
    print("\nWhat would you like to set up?")
    choices = tuple(MODES)
    for number, mode in enumerate(choices, start=1):
        metadata = MODES[mode]
        print(f"\n  {number}. {metadata.title}")
        print(f"     {metadata.description}")
    while True:
        choice = input("Choose an option [1]: ").strip()
        if not choice:
            return choices[0]
        if choice in {"dev", "host", "docker"}:
            return choice
        if choice.isdigit() and 1 <= int(choice) <= len(choices):
            return choices[int(choice) - 1]
        print("Choose 1, 2, or 3.")


def _node_major() -> int | None:
    """Return the installed Node.js major version, or None when it cannot be determined."""
    if shutil.which("node") is None:
        return None
    result = subprocess.run(["node", "--version"], capture_output=True, text=True, check=False)
    major = result.stdout.strip().lstrip("v").split(".", 1)[0]
    return int(major) if result.returncode == 0 and major.isdigit() else None


def check_prerequisites(mode: str) -> None:
    print("\nChecking what you need")
    if shutil.which("docker") is None:
        raise SystemExit("Docker is not installed. Install Docker, start it, and run this wizard again.")
    _run_step("  Docker", ["docker", "info"], success="ready")
    if mode == "docker" and (error := docker_mode_error(sys.platform)):
        raise SystemExit(error)
    if mode in {"dev", "host"}:
        print("  Node.js...", end=" ", flush=True)
        major = _node_major()
        print("ready." if major == NODE_MAJOR else "needs attention.")
        if major != NODE_MAJOR:
            found = f"version {major}" if major else "no working installation"
            raise SystemExit(
                f"Node.js {NODE_MAJOR} is required, but the wizard found {found}. "
                "Install the required version and try again."
            )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Configure and deploy Game Sandbox.")
    parser.add_argument("--mode", choices=("dev", "host", "docker"), help="Skip the interactive mode menu.")
    args = parser.parse_args(argv)
    print("Game Sandbox setup\n")
    print("Welcome. This wizard will save your settings, prepare Game Sandbox, and help you start it.")
    mode = args.mode or choose_mode()
    check_prerequisites(mode)
    if mode == "dev":
        raise SystemExit(run_dev())
    if mode == "host":
        raise SystemExit(run_host())
    raise SystemExit(run_docker())


if __name__ == "__main__":
    try:
        main()
    except (EOFError, KeyboardInterrupt):
        raise SystemExit("\nSetup cancelled.") from None
