"""Synced copy of the Game Sandbox environment modules for local development.

GENERATED by scripts/generate.py from environments/src/game_sandbox_environments/. Do not
edit by hand. The students' agents run against this vanilla-PettingZoo env locally; only the
steppable environment is synced, never the harness, recording store, or metadata layer.

This template targets Flappy Bird. The base scripts read the uniform surface below, so they
stay environment-agnostic across template layers.
"""

from .flappy_bird import NOOP_ACTION, extract_overlay, make_env

ENV_ID = "flappy_bird"
PLAYER_SLOT = "player_0"

__all__ = ["make_env", "extract_overlay", "NOOP_ACTION", "ENV_ID", "PLAYER_SLOT"]
