"""Synced Spades environment for local development.

GENERATED by scripts/generate.py. Do not edit by hand. The harness-side registry entry
(metadata + hooks) is intentionally not synced; locally you build the env directly:

    from sandbox.env import make_env
"""

from .env import AUTO_ACTION, make_env
from .human import make_human_controller
from .overlay import extract_overlay

__all__ = ["make_env", "make_human_controller", "extract_overlay", "AUTO_ACTION"]
